POST http://localhost:3000/api/register
Content-Type: application/json

# { name, email, password, phoneNumber } = req.body;
# Create User
{
    "name" : "testing",
    "email": "testing05@gmail.com",
    "password" : "12345",
    "phoneNumber" : "081234567890"
}

###

GET http://localhost:3000/
Content-Type: application/json