POST https://localhost:3000/
Content-Type: application/json

# { name, email, password, phoneNumber } = req.body;
# Create User
{
    "name" : "Irmansyah",
    "email": "irmansyahmuslimin05@gmail.com",
    "passwword" : "12345",
    "phoneNumber" : "081234567890"
}


