POST http://localhost:3000/api/auth/register
Content-Type: application/json

# { name, email, password, phoneNumber } = req.body;
# Create User
{
    "name" : "K Hanma",
    "email": "testing050503@gmail.com",
    "password" : "1234",
    "phoneNumber" : "0823456323"
}

###

GET http://localhost:3000/
Content-Type: application/json

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "testing05@gmail.com",
    "password" : "123"
}

### Logout

DELETE http://localhost:3000/api/logout
Content-Type: application/json

### Update User 

PUT http://localhost:3000/api/6669a8b49afdd5a6ecdd0324
Content-Type: application/json

{
    "name" : "K Hanma",
    "userId" : "6669a8b49afdd5a6ecdd0324"
} 

### get User

GET http://localhost:3000/api/6669a8b49afdd5a6ecdd0324